export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const ADD_EVENT = 'ADD_EVENT';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS'
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';

export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MEMBERS = 'FETCH_MEMBERS';
