export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';


export const ADD_EVENT = 'ADD_EVENT';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';

export const FETCH_MEMBERS = 'FETCH_MEMBERS';



