export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const ADD_EVENT = 'ADD_EVENT';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS'
